apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: favourable-gerbil-python
  janus-idp.io/tekton: favourable-gerbil-python
  backstage.io/kubernetes-id: favourable-gerbil-python
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: favourable-gerbil-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
