apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: favourable-gerbil-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: favourable-gerbil-python 
  name: favourable-gerbil-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: favourable-gerbil-python
    weight: 100 
